name: Android CI

on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: createProjectFromTemplate
      run: python3 ./scripts/createProject.py
    
    - name: commit jks
      uses: EndBug/add-and-commit@v7 # You can change this to use a specific version
      with:
        add: './config/keystore.jks'
        author_name: workflow
        branch: master
        message: 'add jks'

    - name: Build with Gradle
      run: ./gradlew assembleRelease

    - name: upload artifacts
      uses: actions/upload-artifact@v2.2.3
      with:
        name: APK
        path: app/build/outputs/apk/release
